version: '2.2'

services:
  lb:
    image: traefik:1.7-alpine
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/servers.toml:/servers.toml

      - ../../traefik/acme.json:/acme.json
      - ../../traefik/certs/localhost.crt:/certificates/localhost.crt
      - ../../traefik/certs/localhost.key:/certificates/localhost.key

    command: --api --docker --logLevel=DEBUG
    networks:
      - proxy
    labels:
      - traefik.enable=false


  b:
    build: ../../app/. # A container that exposes an API to show its IP address
    labels:
      - traefik.backend=b
      - traefik.frontend.rule=Host:www.b.com.br
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.port=3000
    scale: 1
    networks:
      - internal
      - proxy
    environment:
      - MESSAGE=b domain
      - PORT=3000

  a:
    build: ../../app/. # A container that exposes an API to show its IP address
    labels:
      - traefik.backend=a
      - traefik.frontend.rule=Host:www.a.com.br
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.port=4000
    scale: 1
    networks:
      - internal
      - proxy
    environment:
      - MESSAGE="a domain"
      - PORT=4000


networks: 
  proxy:
    external: true
  internal:
    external: false